DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS QUIZZES;
DROP TABLE IF EXISTS RESULTS;

CREATE TABLE STUDENTS
(
ID INTEGER PRIMARY KEY,
FIRST_NAME VARCHAR NOT NULL,
LAST_NAME VARCHAR NOT NULL
);

CREATE TABLE QUIZZES
(
ID INTEGER PRIMARY KEY NOT NULL,
SUBJECT VARCHAR,
NUM_QUESTIONS INTEGER,
QUIZ_DATE VARCHAR
);

CREATE TABLE RESULTS
(
STU_ID INT NOT NULL,
QUIZ_ID INT NOT NULL,
SCORE INT NOT NULL
);

INSERT INTO STUDENTS (ID, FIRST_NAME, LAST_NAME) 
VALUES (1, 'John', 'Smith');
	
INSERT INTO QUIZZES (ID, SUBJECT, NUM_QUESTIONS, QUIZ_DATE)
VALUES (1, 'Python Basics', 5, '2015-02-05');


INSERT INTO RESULTS (STU_ID, QUIZ_ID, SCORE)
VALUES (1, 1, 85 );
	
